---
- name: MAJ système
  hosts: all
  become: true
  tasks:
    - name: Apt update + Apt upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - vim
          - plocate
          - bash-completion
          - git
          - net-tools
          - tree